### ISSUE TITLE
Question: Can I store all entities into one JSON?

### ISSUE THREAD

**Issue by tiksn** [cloudscribe/NoDb#3]
I want to store all "table" into one JSON. having so much JSONs bothers me. How can I do that?

**Comment by joeaudette** [comment]
only way you could achieve it with nodb is make a class to represent your table with a list property of another class that represents your rows, then you can save the table object instead of saving each row as separate objects. but that means any time a row changes you have to save the whole table again

or you could use other solutions like sqlite or some other single file data store solution

**Comment by tiksn** [comment]
Thanks for reply. I am creating single file for each row. As an alternative I am thinking to load data from configuration via options, each "table" will be an option. Sqlite sound a bit complex for my "business-card" (personal) website.

**Comment by joeaudette** [comment]
if file system storage is suitable for your small website app, why do you care how many files on disk? 

It is an implementation detail just like the guts of a database, you don't need to look at those files

**Comment by joeaudette** [comment]
just one more thought about this question. file per object is also better because there is less chance for contention in updating a file, whereas with multiple entities in the same file there is a lot more chance for file system contention with different threads trying to update the same file.

**Comment by tiksn** [comment]
Agree. I abandoned idea to have one json per table.
